name: Trigger WDA Action

# Controls when the workflow will run
on:
  workflow_dispatch:
  # Triggers the workflow on push event but only for the branch specified with in []
  push:
    branches: [ feature/enable_CI-CD ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Trigger WDA Action for CI/CD
        run: |
          curl --request POST \
          --url https://api.github.com/repos/tic-oss/wda-server/actions/workflows/main.yml/dispatches \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --header 'X-GitHub-Api-Version: 2022-11-28' \
          --data '{
            "ref": "main"
            }' \